In [1]:
#Creating a simple 2D Array Using Numpy

import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
# Adding The Number to Each elements in the Array . It wont Works in Python List

a=np.array([[1,2,3],[4,5,6]])
b=a+20
print(b)

[[21 22 23]
 [24 25 26]]


In [4]:
# Subtarcting The Number to Each elements in the Array . It wont Works in Python List

a=np.array([[1,2,3],[4,5,6]])
b=a-20
print(b)

[[-19 -18 -17]
 [-16 -15 -14]]


In [6]:
# Multiplying The Number to Each Elements in the Array . It wont Works in Python List

a=np.array([[1,2,3],[4,5,6]])
b=a*20
print(b)

[[ 20  40  60]
 [ 80 100 120]]


In [8]:
# Dividing The Number to Each Elements in the Array . It wont Works in Python List

a=np.array([[1,2,3],[4,5,6]])
b=a/20
print(b)
b=a//20
print(b)

[[0.05 0.1  0.15]
 [0.2  0.25 0.3 ]]
[[0 0 0]
 [0 0 0]]


In [10]:
# Finding The Reminder by Using  Modulo to get from Each Elements

a=np.array([[1,2,3],[4,5,6]])
b=a%2
print(b)


[[1 0 1]
 [0 1 0]]


In [11]:
# Finding The Power of Each Elements inside the Array

a=np.array([[1,2,3],[4,5,6]])
b=a**2
print(b)

[[ 1  4  9]
 [16 25 36]]


In [15]:
# Adding The Matrix Elements and Printing Sum

a=np.array([[1,2,3],[4,5,6]])
b=sum(a)
print(b)
b=np.sum(a)
print(b)

[5 7 9]
21


In [14]:
# Find Maximum in the Array

a=np.array([[1,2,3],[4,5,6]])
b=np.max(a)
print(b)

6


In [16]:
# Find The Minumim in the Array

a=np.array([[1,2,3],[4,5,6]])
b=np.min(a)
print(b)

1


In [18]:
# Adding 2 matrices Elements

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a+b
print(c)

# If Doing the Same in Python List . It will Concatenate
a=[[1,2,3],[4,5,6]]
b=[[1,2,3],[4,5,6]]
c=a+b
print(c)

[[ 2  4  6]
 [ 8 10 12]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [20]:
# Subtracting 2 Matrices Elements

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a-b
print(c)

# If Doing the Same in Python List . It will Shows Error

[[0 0 0]
 [0 0 0]]


In [23]:
# Multiply 2 Matrices Elements

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a*b
print(c)

# If Doing the Same in Python List . It will Shows Error

[[ 1  4  9]
 [16 25 36]]


In [25]:
# Divide 2 matrices Elements

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a/b
print(c)
c=a//b
print(c)

# If Doing the Same in Python List . It will Shows Error

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [26]:
# Find Modulo with 2 Matrices

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a%b
print(c)


[[0 0 0]
 [0 0 0]]


In [27]:
# Find A^b with each Elements

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a**b
print(c)


[[    1     4    27]
 [  256  3125 46656]]


In [28]:
# Generate a N number of Zeros in the Array

a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
# Generate a N number of Ones in the Array

a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
# Print the Order of Matrix (rows,columns)

a=np.array([[1,2,3],[4,5,6]])
print(np.shape(a))

(2, 3)


In [49]:
# Perform Matrix Multiplication

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = np.matmul(a, b)
print(c)
c = np.dot(a, b)
print(c)
c = a@b
print(c)




[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


In [2]:
# Getting Array from The User Input

import numpy as np

rows,columns = map(int,input().split())
arr=np.array([input(f"Enter the Row {i+1} Elements : ").split() for i in range(rows)],dtype=int)
print(arr)


2 2
Enter the Row 1 Element : 1 2 3 4 5
Enter the Row 2 Element : 2 3 4 5 6
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [15]:
# Printing Array Informations

a=np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5],[6,7,8,9,0]])
print(" printing Array\n")
print(a)
print("\n Printing Size of Array : ",end="")
print(np.size(a))
print("\n Printing Shape of Array : ",end="")
print(np.shape(a))
print("\n Printng Dimensions of Array : ",end="")
print(np.ndim(a))
print("\n Printng Data Type of Elements in Array : ",end="")
print(a.dtype)

 printing Array

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]]

 Printing Size of Array : 20

 Printing Shape of Array : (4, 5)

 Printng Dimensions of Array : 2

 Printng Data Type of Elements in Array : int32


In [18]:
# Creating an array with full of some numbers

a=np.full(5,6)
print(a)

[6 6 6 6 6]


In [21]:
# Creating a matrix by mentioning the shape and fill a element

a=np.full((4,4),8 , dtype=int)
print(a)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [2]:
# Creating a Complex Array with real and imaginary Part

import numpy as np
a = np.full((3, 3), 6, dtype = 'complex')
print(a)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [9]:
# Transpose of Matrix

a=np.array([[1,2,3],
            [4,5,6]])

print("Original Matrix ")
print(a)
print("\n Transposed Matrix")
print(a.T)
print("\n Another Way Transposed Matrix")
print(np.transpose(a))

Original Matrix 
[[1 2 3]
 [4 5 6]]

 Transposed Matrix
[[1 4]
 [2 5]
 [3 6]]

 Another Way Transposed Matrix
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# Universal Operations of Numpy

a=np.array([[1,2,3],
            [4,5,6]])
print("printing Array")
print(a)
print("\n Square Root of Array")
print(np.sqrt(a))
print("\n print Sin Values ")
print(np.pi/a)
print("\n Exponential of Array")
print(np.exp(a))
print("\n Logarthimic Functios in Array")
print(np.log10(a))
print("\n Trignometrical Operations ")
print(np.sin(a))

printing Array
[[1 2 3]
 [4 5 6]]

 Square Root of Array
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

 print Sin Values 
[[3.14159265 1.57079633 1.04719755]
 [0.78539816 0.62831853 0.52359878]]

 Exponential of Array
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

 Logarthimic Functios in Array
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]

 Trignometrical Operations 
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [33]:
# Arange Function In Numpy

a=np.arange(20,100,2)
print(a)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [51]:
# Reshaping the Array

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
b=np.arange(8).reshape(2,4)
print(b)

a=np.array([2,4,6,8,10,12,14,16,18,20])
b=a.reshape(2,5)
print(b)

#Reshaping into 3d array
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,2,2)
print(b)



[[0 1 2 3]
 [4 5 6 7]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [57]:
# Linespace Method in Numpy to find the steps of numbers between 2 Numbers

import numpy as np
print(np.linspace(1.0,2.0,20,retstep=True))

(array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ]), 0.05263157894736842)


In [61]:
# Flattening the Array

a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print("Original Array")
print(a)
print("\nFlattened Array")
print(a.flatten())
print("\nUsing Flattened Method")
print(a.flatten("f"))


Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Flattened Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Using Flattened Method
[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]


In [6]:
# Using the Fuction np.core.records.fromrecords to define Datatype for Organizing and Accessing

datatype=[('name','U20'),('Roll Number',int),('Fees',float),('school','U90')]
students=[('Rahul',10,22000,'Sannathi School'),
          ('Varma',15,20000,'Stanford School'),
          ('Ajith',12,25000,'Kingston School'),
          ('Lokesh',13,45000,'Sairam Engineering College')]
students_record=np.core.records.fromrecords(students,dtype=datatype)
print(students_record)
print("\n Priting the Names only")
print(students_record.name)


[('Rahul', 10, 22000., 'Sannathi School')
 ('Varma', 15, 20000., 'Stanford School')
 ('Ajith', 12, 25000., 'Kingston School')
 ('Lokesh', 13, 45000., 'Sairam Engineering College')]

 Priting the Names only
['Rahul' 'Varma' 'Ajith' 'Lokesh']


In [85]:
# Shallow Copy in Numpy

import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# assigning arr to nc 
nc = arr 
  
# both arr and nc have same id 
print("id of arr", id(arr)) 
print("id of nc", id(nc)) 
  
# updating nc 
nc[0]= 12
  
# printing the values 
print("original array- ", arr) 
print("assigned array- ", nc) 

id of arr 2524868346384
id of nc 2524868346384
original array-  [12  4  6  8 10]
assigned array-  [12  4  6  8 10]


In [93]:
# Deep Copy in Numpy

arr = np.array([1,2,3,4,5,6,7,8])
b=arr.copy()
print("Printing Value b")
print(b)
print(f"id of arr = {id(arr)}")
print(f"id of b = {id(b)}")
b[0]=20
print(b)
print(arr)

Printing Value b
[1 2 3 4 5 6 7 8]
id of arr = 2524933669104
id of b = 2524934898096
[20  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]


In [111]:
# Base Function in numpy to print its base

arr=np.array([1,2,3,4,5])
b=arr[2:]
print(id(arr))
print(id(b))
print(b.base is arr)
print(b.view())

2524846854032
2524846853360
True
[3 4 5]


In [121]:
# Appending The Elements At the Last

import numpy as np
arr=np.array([1,2,3,4,5])
a=np.append(arr,[10])
print(a)

# Appending 2 arrays

arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr3=arr1+arr2
print(arr3)

[ 1  2  3  4  5 10]
[ 7  9 11 13 15]


In [3]:
# Axis Parameter in Numpy

import numpy as np

# Creating a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Sum along Axis 0 (sum along columns)
sum_along_axis_0 = np.sum(arr_2d, axis=0)
print("Sum along Axis 0 (columns):", sum_along_axis_0)

# Sum along Axis 1 (sum along rows)
sum_along_axis_1 = np.sum(arr_2d, axis=1)
print("Sum along Axis 1 (rows):", sum_along_axis_1)


Sum along Axis 0 (columns): [5 7 9]
Sum along Axis 1 (rows): [ 6 15]


In [5]:
# Using Axis to Concatenate in rows and columns

import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# Concatenating along Axis 0 (stacking vertically)
concatenated_axis_0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along Axis 0:\n", concatenated_axis_0)

# Concatenating along Axis 1 (stacking horizontally)
concatenated_axis_1 = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along Axis 1:\n", concatenated_axis_1)


Concatenated along Axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along Axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [3]:
# Swapping The Columns  1 and 2 in each Row

import numpy as np

arr1 = np.array([[1, 2, 1],
                 [3, 4, 1],
                 [5, 6, 1],
                 [7, 8, 1]])
print("Array Before Swapping")
print(arr1)
arr1[:,[1,2]] = arr1[:,[2,1]]
print("\nArray After Swapping")
print(arr1)



Array Before Swapping
[[1 2 1]
 [3 4 1]
 [5 6 1]
 [7 8 1]]

Array After Swapping
[[1 1 2]
 [3 1 4]
 [5 1 6]
 [7 1 8]]


In [5]:
# Swapping The Rows row 0 and 2

import numpy as np

arr1 = np.array([[1, 2, 1],
                 [3, 4, 1],
                 [5, 6, 1],
                 [7, 8, 1]])
print("Array Before Swapping")
print(arr1)
arr1[[0,2],:] = arr1[[2,0],:]
print("\nArray After Swapping")
print(arr1)



Array Before Swapping
[[1 2 1]
 [3 4 1]
 [5 6 1]
 [7 8 1]]

Array After Swapping
[[5 6 1]
 [3 4 1]
 [1 2 1]
 [7 8 1]]


In [22]:
# Insert New axis Using np.newaxis to convert 1d-2d-3d-....nd
"""
1D array will become 2D array
2D array will become 3D array
3D array will become 4D array
4D array will become 5D array
"""

import numpy as np

# Creating a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Inserting a new axis along the rows
arr_3d_row = arr_2d[np.newaxis, :, :]

# Inserting a new axis along the columns
arr_3d_col = arr_2d[:, np.newaxis, :]

# Inserting new axes along both rows and columns
arr_3d_both = arr_2d[:, :, np.newaxis]

print("Original 2D array:")
print(arr_2d)

print("\nArray with a new axis along the rows (3D):")
print(arr_3d_row)

print("\nArray with a new axis along the columns (3D):")
print(arr_3d_col)

print("\nArray with new axes along both rows and columns (3D):")
print(arr_3d_both)


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with a new axis along the rows (3D):
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

Array with a new axis along the columns (3D):
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]

Array with new axes along both rows and columns (3D):
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [5]:
# Insert New axis Using numpy.expand_dims()


import numpy as np 
  
  
x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=1).shape 
print(y) 

(3, 1, 4)


In [6]:
# Importing numpy as np
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [7]:
# Python program explaining
# eigh() function
 
from numpy import linalg as geek
 
# Creating an array using array 
# function
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :",a)
 
# calculating an eigen value
# using eigh() function
c, d = geek.eigh(a)
 
print("Eigen value is :", c)
print("Eigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is : [0.17157288 5.82842712]
Eigen value is : [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [12]:
# Python program explaining 
# numpy.random.ranf() function 

# importing numpy 
import numpy as geek 


# output random float value 
out_val = geek.random.ranf() 
print ("Output random float value : ", out_val) 


Output random float value :  0.9209205573565269


In [13]:
# Python program explaining 
# numpy.random.random() function 

# importing numpy 
import numpy as geek 

# output array 
out_arr = geek.random.random((2, 3, 2)) 
print ("Output 3D Array filled with random floats : ", out_arr) 


Output 3D Array filled with random floats :  [[[0.73453648 0.80015089]
  [0.99611113 0.08734216]
  [0.9787324  0.91547675]]

 [[0.52745997 0.14555556]
  [0.80269588 0.26386803]
  [0.69731769 0.71614958]]]


In [17]:
import numpy as np

# Example using numpy.random.shuffle
arr_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr_shuffle)
print("Shuffled array (in-place):", arr_shuffle)

# Example using numpy.random.permutation
arr_perm = np.array([1, 2, 3, 4, 5])
shuffled_arr = np.random.permutation(arr_perm)
print("Original array:", arr_perm)
print("Shuffled array (copy):", shuffled_arr)


Shuffled array (in-place): [4 3 2 1 5]
Original array: [1 2 3 4 5]
Shuffled array (copy): [2 1 3 5 4]


In [32]:
import numpy as np

# Generate 1000 random values from a geometric distribution with probability 0.65
random_values = np.random.geometric(0.01, size=100)
print(random_values)

[236  15 345 217  22  24 182  33 163 166 227  37 123   4  98 134  52  40
  46  15  37   1  98  82  18  36  12  96 101 384  92  17  79 152 238 141
 170  72   1 164  72 106  62 258  38  58   9 129  30  78 134 120 105  33
  56 177   4  10 151  17 152  18  17 469  48 202  76 107  24 118  47  16
  69 277  29   6   6  83 162   8 220   4  84 287 154  17 323 160 268  74
  10  75 117 226 108 130  37 240  29  44]


In [33]:
# Python program to demonstrate 
# the use of index arrays.
import numpy as np

# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)

# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [39]:

# Python Program illustrating 
# numpy.compress method 
  
import numpy as geek 
  
array = geek.arange(10).reshape(5, 2) 
print("Original array : \n", array) 
  
a = geek.compress([0, 1], array, axis=0) 
print("\nSliced array : \n", a) 
  
a = geek.compress([1,0], array, axis=1) 
print("\nSliced array : \n", a) 

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Sliced array : 
 [[2 3]]

Sliced array : 
 [[0]
 [2]
 [4]
 [6]
 [8]]


In [7]:

# importing libraries
import numpy as np
 
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = -1)        
print ("Along first axis : \n", arr1) 

Along first axis : 
 [[12 15]
 [ 1 10]]
